# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sci_pb2 as sci__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sci_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DWHExternalServiceStub(object):
    """==================== DWH外部工具服务 ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadDocument = channel.unary_unary(
                '/dwh_api.DWHExternalService/UploadDocument',
                request_serializer=sci__pb2.UploadDocumentRequest.SerializeToString,
                response_deserializer=sci__pb2.UploadDocumentResponse.FromString,
                _registered_method=True)
        self.ParseDocument = channel.unary_stream(
                '/dwh_api.DWHExternalService/ParseDocument',
                request_serializer=sci__pb2.ParseDocumentRequest.SerializeToString,
                response_deserializer=sci__pb2.ParseDocumentResponse.FromString,
                _registered_method=True)
        self.GenerateKnowledgeGraph = channel.unary_unary(
                '/dwh_api.DWHExternalService/GenerateKnowledgeGraph',
                request_serializer=sci__pb2.GenerateKnowledgeGraphRequest.SerializeToString,
                response_deserializer=sci__pb2.GenerateKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.QueryGraphRAG = channel.unary_unary(
                '/dwh_api.DWHExternalService/QueryGraphRAG',
                request_serializer=sci__pb2.QueryGraphRAGRequest.SerializeToString,
                response_deserializer=sci__pb2.QueryGraphRAGResponse.FromString,
                _registered_method=True)


class DWHExternalServiceServicer(object):
    """==================== DWH外部工具服务 ====================

    """

    def UploadDocument(self, request, context):
        """1. 上传文档 - 对应func.py中各函数调用send_request前的数据准备阶段
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseDocument(self, request, context):
        """2. 解析返回（流式） - 对应func.py中send_request调用后的结果处理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateKnowledgeGraph(self, request, context):
        """3. 生成图谱 - 基于解析结果构建知识图谱
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryGraphRAG(self, request, context):
        """4. 查询GraphRAG - 基于知识图谱进行检索增强生成
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DWHExternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=sci__pb2.UploadDocumentRequest.FromString,
                    response_serializer=sci__pb2.UploadDocumentResponse.SerializeToString,
            ),
            'ParseDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=sci__pb2.ParseDocumentRequest.FromString,
                    response_serializer=sci__pb2.ParseDocumentResponse.SerializeToString,
            ),
            'GenerateKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKnowledgeGraph,
                    request_deserializer=sci__pb2.GenerateKnowledgeGraphRequest.FromString,
                    response_serializer=sci__pb2.GenerateKnowledgeGraphResponse.SerializeToString,
            ),
            'QueryGraphRAG': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryGraphRAG,
                    request_deserializer=sci__pb2.QueryGraphRAGRequest.FromString,
                    response_serializer=sci__pb2.QueryGraphRAGResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dwh_api.DWHExternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dwh_api.DWHExternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DWHExternalService(object):
    """==================== DWH外部工具服务 ====================

    """

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dwh_api.DWHExternalService/UploadDocument',
            sci__pb2.UploadDocumentRequest.SerializeToString,
            sci__pb2.UploadDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dwh_api.DWHExternalService/ParseDocument',
            sci__pb2.ParseDocumentRequest.SerializeToString,
            sci__pb2.ParseDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dwh_api.DWHExternalService/GenerateKnowledgeGraph',
            sci__pb2.GenerateKnowledgeGraphRequest.SerializeToString,
            sci__pb2.GenerateKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryGraphRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dwh_api.DWHExternalService/QueryGraphRAG',
            sci__pb2.QueryGraphRAGRequest.SerializeToString,
            sci__pb2.QueryGraphRAGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
