apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dora.fullname" . }}-websocket
  labels:
    {{- include "dora.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  replicas: {{ .Values.websocket.replicaCount }}
  selector:
    matchLabels:
      {{- include "dora.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: websocket
  template:
    metadata:
      labels:
        {{- include "dora.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: websocket
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dora.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: websocket
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              sleep 10 && \
              daphne --bind 0.0.0.0 --port 8081 app.asgi:application
          ports:
            - name: ws
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: ws
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: ws
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.websocket.resources | nindent 12 }}
          env:
            {{- include "dora.backendEnv" . | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dora.fullname" . }}-websocket
  labels:
    {{- include "dora.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "dora.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
