from typing import Any, Dict, List

PC_V2_DRUGS_AND_TRIALS_RESPONSE: List[Dict[str, Any]] = [
    {
        "compound_id": "CHEMBL514200",
        "compound_name": "TALMAPIMOD",
        "disease_id": "EFO_0000685",
        "disease_name": "rheumatoid arthritis",
        "drug_name": "SCIO-469",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000112062",
        "gene_symbol": "MAPK14",
        "nct_id": "NCT00089921",
        "phase": ["Phase 1"],
        "primary_completion_date": 2005,
        "sponsor_lead": "Scios, Inc.",
    },
    {
        "compound_id": "CHEMBL514201",
        "compound_name": "TALMAPIMOD",
        "disease_id": "MONDO_0003225",
        "disease_name": "bone marrow disease",
        "drug_name": "SCIO-469",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000112062",
        "gene_symbol": "MAPK14",
        "nct_id": "EMPTY_DATE",
        "phase": ["Phase 1"],
        "primary_completion_date": None,
        "sponsor_lead": "Scios, Inc.",
    },
    {
        "compound_id": "CHEMBL514201",
        "compound_name": "TALMAPIMOD",
        "disease_id": "EFO_0000198",
        "disease_name": "myelodysplastic syndrome",
        "drug_name": "SCIO-469",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000112062",
        "gene_symbol": "MAPK14",
        "nct_id": "NCT00113893",
        "phase": ["Phase 2"],
        "primary_completion_date": 2007,
        "sponsor_lead": "Scios, Inc.",
    },
    {
        "compound_id": "CHEMBL514201",
        "compound_name": "TALMAPIMOD",
        "disease_id": "MONDO_0005374",
        "disease_name": "bone marrow neoplasm",
        "drug_name": "SCIO-469",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000112062",
        "gene_symbol": "MAPK14",
        "nct_id": "LONG_DATE",
        "phase": ["Phase 3"],
        "primary_completion_date": "2007-04-01",
        "sponsor_lead": "Scios, Inc.",
    },
    {
        "compound_id": "CHEMBL514201",
        "compound_name": "TALMAPIMOD",
        "disease_id": None,
        "disease_name": None,
        "drug_name": "SCIO-469",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000112062",
        "gene_symbol": "MAPK14",
        "nct_id": "EMPTY_DISEASE_FIELDS",
        "phase": ["Phase 4"],
        "primary_completion_date": "2007-04-01",
        "sponsor_lead": "Scios, Inc.",
    },
    {
        "compound_id": "CHEMBL1230065",
        "compound_name": "BMS-582949",
        "disease_id": "EFO_0000685",
        "disease_name": "rheumatoid arthritis",
        "drug_name": "BMS-582949 and Methotrexate",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000112062",
        "gene_symbol": "MAPK14",
        "nct_id": "TWO_PHASES",
        "phase": ["Phase 1", "Phase 2"],
        "primary_completion_date": None,
        "sponsor_lead": "Bristol-Myers Squibb",
    },
]
