DISEASE = "B-cell acute lymphoblastic leukemia"
DISEASE_EFO_ID = "EFO_0000094"
DISEASE_METADATA = {
    DISEASE_EFO_ID: {
        "name": DISEASE,
        "synonyms": [
            "precursor B lymphoblastic leukemia/lymphoma",
        ],
    }
}
DRUGS_CLINICAL_TRIALS_CLINICAL_STUDIES_TOOL_ANSWER = [
    {"nct_id": "NCT05602194", "phase": "Phase 3", "drug": "calaspargase pegol", "molecule_type": "Enzyme"},
    {"nct_id": "NCT05602194", "phase": "Phase 3", "drug": "pegaspargase", "molecule_type": "Enzyme"},
    {"nct_id": "NCT05602194", "phase": "Phase 3", "drug": "levocarnitine", "molecule_type": "Small Molecule"},
    {"nct_id": "NCT02167360", "phase": "Phase 2", "drug": "ctl019", "molecule_type": "Cell"},
    {"nct_id": "JPRN", "phase": "Phase 3", "drug": "prednisone-response", "molecule_type": "Small Molecule"},
]

DRUGS_CLINICAL_TRIALS_TOP_DRUGS_TOOL_ASNWER = [
    "CTL019",
    "Calaspargase Pegol",
    "Levocarnitine",
    "Pegaspargase",
    "prednisone-response",
]

PC_V2_DRUGS_AND_TRIALS_RESPONSE = [
    {
        "compound_id": "CHEMBL3301574",
        "compound_name": "TISAGENLECLEUCEL",
        "disease_id": "EFO_0000094",
        "disease_name": "B-cell acute lymphoblastic leukemia",
        "drug_name": "CTL019",
        "drug_type": "Cell",
        "gene_id": "ENSG00000177455",
        "gene_symbol": "CD19",
        "nct_id": "NCT02167360",
        "phase": ["Phase 2"],
        "primary_completion_date": None,
        "sponsor_lead": "Abramson Cancer Center at Penn Medicine",
        "title": "Study of Efficacy and Safety of CTL019 in Adult ALL Patients",
        "trial_id": "NCT02167360",
        "url": "https://clinicaltrials.gov/study/NCT02167360",
    },
    {
        "compound_id": "CHEMBL2108728",
        "compound_name": "CALASPARGASE PEGOL",
        "disease_id": "EFO_0000094",
        "disease_name": "B-cell acute lymphoblastic leukemia",
        "drug_name": "Calaspargase Pegol",
        "drug_type": "Enzyme",
        "gene_id": None,
        "gene_symbol": None,
        "nct_id": "NCT05602194",
        "phase": ["Phase 3"],
        "primary_completion_date": "2027-12-31",
        "sponsor_lead": "Children's Oncology Group",
        "title": "Studying the Effect of Levocarnitine in Protecting the Liver ",
        "trial_id": "NCT05602194",
        "url": "https://clinicaltrials.gov/study/NCT05602194",
    },
    {
        "compound_id": "CHEMBL2108546",
        "compound_name": "PEGASPARGASE",
        "disease_id": "EFO_0000094",
        "disease_name": "B-cell acute lymphoblastic leukemia",
        "drug_name": "Pegaspargase",
        "drug_type": "Enzyme",
        "gene_id": None,
        "gene_symbol": None,
        "nct_id": "NCT05602194",
        "phase": ["Phase 3"],
        "primary_completion_date": "2027-12-31",
        "sponsor_lead": "Children's Oncology Group",
        "title": "Studying the Effect of Levocarnitine in Protecting the Liver ",
        "trial_id": "NCT05602194",
        "url": "https://clinicaltrials.gov/study/NCT05602194",
    },
    {
        "compound_id": "CHEMBL1149",
        "compound_name": "LEVOCARNITINE",
        "disease_id": "EFO_0000094",
        "disease_name": "B-cell acute lymphoblastic leukemia",
        "drug_name": "Levocarnitine",
        "drug_type": "Small Molecule",
        "gene_id": None,
        "gene_symbol": None,
        "nct_id": "NCT05602194",
        "phase": ["Phase 3"],
        "primary_completion_date": "2027-12-31",
        "sponsor_lead": "Children's Oncology Group",
        "title": "Studying the Effect of Levocarnitine in Protecting the Liver ",
        "trial_id": "NCT05602194",
        "url": "https://clinicaltrials.gov/study/NCT05602194",
    },
    {
        "compound_id": "CHEMBL635",
        "compound_name": "PREDNISONE",
        "disease_id": "EFO_0000094",
        "disease_name": "B-cell acute lymphoblastic leukemia",
        "drug_name": "prednisone-response",
        "drug_type": "Small Molecule",
        "gene_id": "ENSG00000113580",
        "gene_symbol": "NR3C1",
        "nct_id": "JPRN",
        "phase": ["Phase 3"],
        "primary_completion_date": None,
        "sponsor_lead": "Katsuyoshi Koh",
        "title": "A phase III randomized trial for B-cell precursor ALL",
        "trial_id": "JPRN",
        "url": "https://jrct.niph.go.jp/latest-detail/jRCTs041210040",
    },
]

GENETIC_VARIANTS = [
    {
        "dbsnp": "rs121908446",
        "name": "p.Arg1305Ter",
        "clin_sig_corrected": "pathogenic",
        "type": "SNV",
        "source": "Clinvar",
    },
    {
        "dbsnp": "rs113993961",
        "name": "c.3139-1G>C",
        "clin_sig_corrected": "pathogenic",
        "type": "SNV",
        "source": "Clinvar",
    },
    {
        "dbsnp": "rs748860208",
        "name": "p.Thr1011fs",
        "clin_sig_corrected": "pathogenic",
        "type": "Deletion",
        "source": "Clinvar",
    },
    {
        "dbsnp": "rs373806031",
        "name": "p.Tyr57Ter",
        "clin_sig_corrected": "pathogenic",
        "type": "SNV",
        "source": "Clinvar",
    },
    {
        "dbsnp": "rs-1",
        "name": "p.Val1082fs",
        "clin_sig_corrected": "pathogenic",
        "type": "Deletion",
        "source": "Clinvar",
    },
]
