# Generated by Django 4.2 on 2024-09-12 05:40

import uuid

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomBibliographyFile",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("name", models.CharField(max_length=500)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[("pdf", "pdf"), ("unsupported", "unsupported")],
                        default="pdf",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "uploaded"),
                            ("uploading", "uploading"),
                            ("processed", "processed"),
                            ("failed", "failed"),
                        ],
                        default="uploading",
                        max_length=50,
                    ),
                ),
                ("cleaned_text", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomBibliographyChunkEmbeddings",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("chunk_text", models.TextField()),
                ("embeddings", pgvector.django.vector.VectorField(dimensions=768, null=True)),
                (
                    "custom_bibliography_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bibliography.custombibliographyfile"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="custombibliographyfile",
            constraint=models.CheckConstraint(
                check=models.Q(("format__in", ("pdf", "unsupported"))),
                name="bibliography_custombibliographyfile_format_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="custombibliographyfile",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ("uploaded", "uploading", "processed", "failed"))),
                name="bibliography_custombibliographyfile_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="custombibliographychunkembeddings",
            index=pgvector.django.indexes.HnswIndex(
                fields=["embeddings"], name="bibliography_embeddings_hnsw", opclasses=["vector_l2_ops"]
            ),
        ),
    ]
