# Generated by Django 4.2 on 2024-09-24 07:13

import pgvector.django.vector
from django.db import migrations


def clear_old_embeddings(apps, schema_editor):
    CustomBibliographyChunkEmbeddings = apps.get_model("bibliography", "CustomBibliographyChunkEmbeddings")
    CustomBibliographyChunkEmbeddings.objects.update(embeddings=None)


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0002_custombibliographyfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custombibliographychunkembeddings",
            name="embeddings",
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
        migrations.RunPython(clear_old_embeddings),
    ]
