# Generated by Django 4.2 on 2024-09-26 23:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0003_alter_custombibliographychunkembeddings_embeddings"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebBibliography",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("metadata", models.JSONField(default=dict)),
                ("chunks", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name_plural": "Web Bibliographies",
            },
        ),
    ]
