# Generated by Django 4.2 on 2024-10-09 23:37

import hashlib

from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def delete_existing_web_bibliographies(apps, schema_editor):
    WebBibliography = apps.get_model("bibliography", "WebBibliography")
    Bibliography = apps.get_model("bibliography", "Bibliography")
    ContentType = apps.get_model("contenttypes", "ContentType")

    web_bib_content_type = ContentType.objects.get_for_model(WebBibliography)

    web_bib_ids = WebBibliography.objects.values_list("id", flat=True)

    Bibliography.objects.filter(content_type=web_bib_content_type, object_id__in=web_bib_ids).delete()

    WebBibliography.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0004_webbibliography"),
    ]

    operations = [
        migrations.RunPython(delete_existing_web_bibliographies),
        migrations.AddField(
            model_name="webbibliography",
            name="hashed_link",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
