from django.conf import settings

API_V1_VERSION = "v1"
API_V2_VERSION = "v2"

PHARMACOGNITIVE_API_URL = settings.PHARMACOGNITIVE_API_URL
PC_API_V2_TOKEN = settings.PHARMACOGNITIVE_API_V2_TOKEN
API_KEY_PLACEHOLDER = "?api_key={api_key}"
PC_API_URL_V1 = f"{PHARMACOGNITIVE_API_URL}?key={settings.PHARMACOGNITIVE_API_KEY}"
CACHING_TIME = settings.PHARMACOGNITIVE_CACHING_TIME
