# Generated by Django 4.2 on 2024-06-25 08:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedIP",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("blacklist_starts_at", models.DateTimeField()),
                ("blacklist_ends_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
