# Generated by Django 4.2 on 2024-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_logrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistedip",
            options={},
        ),
        migrations.AddIndex(
            model_name="blacklistedip",
            index=models.Index(fields=["ip_address"], name="general_bla_ip_addr_61d49f_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedip",
            index=models.Index(
                fields=["ip_address", "blacklist_ends_at"], name="general_bla_ip_addr_080129_idx"
            ),
        ),
    ]
