# Generated by Django 4.2 on 2024-08-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_alter_blacklistedip_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistedip",
            options={"ordering": ["-blacklist_ends_at"]},
        ),
    ]
