server {
    listen 80;
    server_name localhost;
    charset utf-8;
    server_tokens off;
    client_max_body_size 0;
    add_header Strict-Transport-Security "max-age=300;" always;

    location ~* /static/(admin|img|drf_spectacular_sidecar|dist|users) {
       root /var/www;
    }

    location / {
        proxy_pass http://frontend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ~* /(api|users|admin|openapi) {
        include /etc/nginx/uwsgi_params;
        uwsgi_pass dora_backend:8080;
        uwsgi_read_timeout 3600;
        uwsgi_send_timeout 3600;
        uwsgi_param X-Real-IP $remote_addr;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /ws/ {
        proxy_pass http://dora_backend_ws:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /s3/ {
        rewrite ^/s3/(.*) /$1 break;
        # proxy_pass http://cloudserver:8000;
        # proxy_set_header Host cloudserver:8000;
        # proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection "upgrade";

        proxy_pass http://s3proxy:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Remove headers that might interfere with S3 signature validation
        proxy_set_header Content-Type "";
        proxy_set_header Content-MD5 "";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
