# Generated by Django 4.2 on 2024-05-31 03:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kernel", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("user_inputs", models.JSONField(verbose_name="User Inputs")),
                ("title", models.CharField(blank=True, max_length=512, null=True, verbose_name="Title")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("section_generating", "Section Generating"),
                            ("section_generated", "Section Generated"),
                            ("plan_generating", "Plan Generating"),
                            ("plan_generated", "Plan Generated"),
                            ("content_generating", "Content Generating"),
                            ("content_generated", "Content Generated"),
                        ],
                        default="section_generated",
                        max_length=50,
                        verbose_name="Stage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="initialized",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kernel.template",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("slug", models.CharField(blank=True, max_length=50, null=True, verbose_name="Slug")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="initialized",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("prompt", models.TextField(blank=True, null=True, verbose_name="Prompt")),
                ("plan_prompt", models.TextField(blank=True, null=True, verbose_name="Plan Prompt")),
                ("plan", models.TextField(blank=True, null=True, verbose_name="Plan")),
                ("custom_data", models.TextField(blank=True, null=True, verbose_name="Custom Data")),
                ("requires_plan", models.BooleanField(default=False, verbose_name="Requires Plan")),
                ("is_title", models.BooleanField(default=False, verbose_name="Is Title")),
                ("tools", models.JSONField(blank=True, null=True, verbose_name="Tools")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="Result")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sections",
                        to="documents.section",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
