# Generated by Django 4.2 on 2024-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="generation_log",
            field=models.JSONField(
                blank=True,
                help_text="Contains error messages and other information related to the generation process.",
                null=True,
                verbose_name="Generation Log",
            ),
        ),
    ]
