# Generated by Django 4.2 on 2024-06-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernel", "0001_initial"),
        ("documents", "0002_section_generation_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kernel.template",
                verbose_name="Template",
            ),
        ),
    ]
