# Generated by Django 4.2 on 2024-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(default="New document draft", max_length=512, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
