# Generated by Django 4.2 on 2024-07-10 07:53

from django.db import migrations, models


def create_document_template_json(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    for document in Document.objects.all():
        document.template_json = document.template.template_json
        document.save()


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="template_json",
            field=models.JSONField(default={}, verbose_name="Template JSON"),
            preserve_default=False,
        ),
        migrations.RunPython(create_document_template_json),
    ]
