# Generated by Django 4.2 on 2024-08-26 05:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0006_section_is_edited_section_refined_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("document_id", models.UUIDField(verbose_name="Document ID")),
                ("section_id", models.UUIDField(blank=True, null=True, verbose_name="Section ID")),
                ("like", models.BooleanField(blank=True, null=True, verbose_name="Like")),
                ("detail", models.TextField(blank=True, null=True, verbose_name="Detail")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["document_id", "section_id"], name="documents_f_documen_f8a700_idx"),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(fields=("document_id", "section_id"), name="unique_feedback"),
        ),
    ]
