# Generated by Django 4.2 on 2024-08-29 06:20

from django.db import migrations, models

import users.defs


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_feedback_feedback_documents_f_documen_f8a700_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="document",
            name="publication_settings",
            field=models.JSONField(
                default=users.defs.get_default_publication_settings, verbose_name="Publication Settings"
            ),
        ),
    ]
