# Generated by Django 4.2 on 2024-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_feedback_options_document_publication_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="bibliographies",
            field=models.JSONField(blank=True, null=True, verbose_name="Bibliographies"),
        ),
    ]
