# Generated by Django 4.2 on 2024-09-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_document_bibliographies"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feedback",
            name="unique_feedback",
        ),
    ]
