# Generated by Django 4.2 on 2024-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_remove_feedback_unique_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mermaid_code",
            field=models.TextField(blank=True, null=True, verbose_name="mermaid_code"),
        ),
        migrations.AddField(
            model_name="document",
            name="mermaid_svg_diagram",
            field=models.TextField(blank=True, null=True, verbose_name="mermaid_svg_diagram"),
        ),
    ]
