# Generated by Django 4.2 on 2024-11-27 09:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0011_document_mermaid_code_document_mermaid_svg_diagram"),
    ]

    operations = [
        migrations.CreateModel(
            name="MermaidDiagram",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "diagram_type",
                    models.CharField(
                        choices=[
                            ("FLOWCHART", "Flowchart"),
                            ("STATE", "State"),
                            ("TIMELINE", "Timeline"),
                            ("SEQUENCE", "Sequence"),
                        ],
                        max_length=30,
                        verbose_name="Diagram Type",
                    ),
                ),
                ("svg_diagram", models.TextField(blank=True, null=True, verbose_name="svg_diagram")),
                ("mermaid_code", models.TextField(blank=True, null=True, verbose_name="mermaid_code")),
                (
                    "document_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="document",
            name="mermaid_diagram",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="documents.mermaiddiagram",
                verbose_name="MermaidDiagram",
            ),
        ),
    ]
