# Generated by Django 4.2 on 2024-12-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_mermaiddiagram_document_mermaid_diagram"),
    ]

    operations = [migrations.RenameField(model_name="document", old_name="user_inputs", new_name="settings")]
