# Generated by Django 4.2 on 2025-01-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_rename_document_user_inputs_to_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="settings",
            field=models.JSONField(verbose_name="Settings"),
        ),
        migrations.AlterField(
            model_name="document",
            name="stage",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("content_generating", "Content Generating"),
                    ("content_generated", "Content Generated"),
                    ("polishing", "Polishing"),
                    ("polished", "Polished"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Stage",
            ),
        ),
    ]
