# Generated by Django 4.2 on 2025-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_alter_document_settings_alter_document_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": (("can_view_all_documents", "Can view all documents"),),
                "managed": False,
            },
        ),
    ]
