# Generated by Django 4.2 on 2025-02-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_custompermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custompermission",
            options={
                "managed": False,
                "permissions": (("can_access_all_documents", "Can access all documents"),),
            },
        ),
    ]
