# Generated by Django 4.2 on 2025-02-24 09:08

from django.db import migrations, models

from documents.transparency.utils import create_document_generation_log


def initialize_document_generation_logs(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    for document in Document.objects.all():
        document.generation_log = create_document_generation_log(document)
        document.save()


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_alter_custompermission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="generation_log",
            field=models.JSONField(blank=True, null=True, verbose_name="Generation Log"),
        ),
        migrations.RunPython(initialize_document_generation_logs),
    ]
