# Generated by Django 4.2 on 2025-03-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_document_generation_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Slug"),
        ),
    ]
