# Generated by Django 4.2 on 2025-10-30 01:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("documents", "0018_alter_section_slug")]

    operations = [
        migrations.CreateModel(
            name="DocumentResearchSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "chat_history",
                    models.JSONField(default=list, verbose_name="Chat History"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("waiting_user", "Waiting User"),
                            ("researching", "Researching"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Thread ID"
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Agent ID"
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Run ID"
                    ),
                ),
                (
                    "last_message_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Last Message ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "abstract": False},
        )
    ]
