# Generated by Django 4.2 on 2025-11-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0019_documentresearchsession")]

    operations = [
        migrations.AddField(
            model_name="documentresearchsession",
            name="processing_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when processing started, used to prevent duplicate processing",
                null=True,
                verbose_name="Processing Started At",
            ),
        ),
        migrations.AlterField(
            model_name="documentresearchsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("waiting_user", "Waiting User"),
                    ("researching", "Researching"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="idle",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
