# Generated by Django 4.2 on 2025-11-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0020_documentresearchsession_processing_started_at_and_more")
    ]

    operations = [
        migrations.RemoveField(model_name="documentresearchsession", name="agent_id"),
        migrations.RemoveField(
            model_name="documentresearchsession", name="last_message_id"
        ),
        migrations.RemoveField(model_name="documentresearchsession", name="run_id"),
        migrations.RemoveField(model_name="documentresearchsession", name="thread_id"),
        migrations.AddField(
            model_name="documentresearchsession",
            name="research_brief",
            field=models.TextField(
                blank=True, null=True, verbose_name="Research Brief"
            ),
        ),
        migrations.AddField(
            model_name="documentresearchsession",
            name="response_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Response ID"
            ),
        ),
        migrations.AlterField(
            model_name="documentresearchsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("pending", "Pending"),
                    ("waiting_user", "Waiting User"),
                    ("researching", "Researching"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="idle",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
