"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import platform
from pathlib import Path

import environ
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from kernel.embeddings.embedding_utils import validate_embedding_openai_api_configs

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    PHARMACOGNITIVE_CACHING_ENABLED=(bool, False),
    EXTERNAL_API_MAX_RETRIES=(int, 3),
    EXTERNAL_API_RETRY_WAIT=(int, 0),
    PHARMACOGNITIVE_CONTEXT_SEARCH_MODE_ENABLED=(bool, False),
    PHARMACOGNITIVE_SYNONYMS_SEARCH_MODE_ENABLED=(bool, False),
    PHARMACOGNITIVE_MAX_REQUEST_TIMEOUT=(int, 30),
    EXTERNAL_API_MAX_REQUEST_TIMEOUT=(int, None),
    OPENAI_API_TIMEOUT=(int, 120),
    OPENAI_API_TYPE=(str, "azure"),
    GENERATION_RETRY_TIMES=(int, 1),
    TOOL_EXECUTION_COUNT_LIMIT=(bool, False),
    TOOL_MAX_EXECUTION_COUNT=(int, 10),
    AGENT_EXECUTOR_MAX_ITERATIONS=(int, 15),
    PANDAOMICS_CLIENT_USE_SSL=(bool, True),
    ENVIRONMENT=(str, "development"),
    EDITION=(str, "standalone"),
    MAXIMUM_CONCURRENT_DOCUMENTS_PER_USER=(int, 5),
    STRIPE_API_PUBLISHABLE_KEY=(str, None),
    STRIPE_API_SECRET_KEY=(str, None),
    STRIPE_WEBHOOK_SECRET=(str, None),
    STRIPE_PRICING_TABLE_ID=(str, None),
    STRIPE_CUSTOMER_PORTAL_RETURN_URL=(str, None),
    GENERATION_TASK_TIMEOUT=(int, 3600),
    CSRF_TRUSTED_ORIGINS=(str, None),
    ALLOWED_HOSTS=(list, ["*"]),
    USE_PHOENIX=(bool, False),
    TEST_RUN=(bool, False),
    MERMAID_SERVER_URL=(str, None),
    WEBSEARCH_EMBEDDING_REQUEST_INTERVAL=(int, 30),
    BACKUP_OPENAI_API_MODEL=(str, None),
    BACKUP_OPENAI_API_BASE_URL=(str, None),
    BACKUP_OPENAI_API_VERSION=(str, None),
    BACKUP_OPENAI_API_DEPLOYMENT_NAME=(str, None),
    BACKUP_OPENAI_API_KEY=(str, None),
    BACKUP_OPENAI_API_TYPE=(str, None),
    BACKUP_O1_OPENAI_API_MODEL=(str, None),
    BACKUP_O1_OPENAI_API_BASE_URL=(str, None),
    BACKUP_O1_OPENAI_API_VERSION=(str, None),
    BACKUP_O1_OPENAI_API_DEPLOYMENT_NAME=(str, None),
    BACKUP_O1_OPENAI_API_KEY=(str, None),
    BACKUP_O1_OPENAI_API_TYPE=(str, None),
    IS_BIBLIOGRAPHY_ENABLED=(bool, False),
    IS_WEBSEARCH_ENABLED=(bool, False),
    PANDAOMICS_CLIENT_API_BASE=(str, None),
    PANDAOMICS_CLIENT_TOKEN=(str, None),
    FROM_EMAIL=(str, None),
    AWS_ACCESS_KEY_ID=(str, None),
    AWS_SECRET_ACCESS_KEY=(str, None),
    AWS_SES_REGION_NAME=(str, None),
    AWS_SES_REGION_ENDPOINT=(str, None),
    AWS_STORAGE_BUCKET=(str, None),
    AWS_STORAGE_REGION=(str, None),
    S3_ENDPOINT_URL=(str, None),
    # Azure Blob Storage settings
    AZURE_STORAGE_CONNECTION_STRING=(str, None),
    AZURE_STORAGE_CONTAINER=(str, None),
    AZURE_STORAGE_LOCATION=(str, None),
    AZURE_STORAGE_ACCOUNT_NAME=(str, None),
    AZURE_STORAGE_ACCOUNT_KEY=(str, None),
    AZURE_STORAGE_AUTO_CREATE_CONTAINER=(bool, False),
    # Optional: override the default Azure domain suffix for sovereign clouds
    # (China, Government, Germany, etc.)
    # Example: AZURE_STORAGE_DOMAIN_SUFFIX=blob.core.chinacloudapi.cn
    AZURE_STORAGE_DOMAIN_SUFFIX=(str, "blob.core.windows.net"),
    HUGGINFACE_API=(str, None),
    HUGGINFACE_AUTHORIZATION_TOKEN=(str, None),
    SOCIALACCOUNT_PROVIDERS=(dict, {}),
    SERPER_API_KEY=(str, None),
    PHARMACOGNITIVE_API_URL=(str, None),
    PHARMACOGNITIVE_API_KEY=(str, None),
    PHARMACOGNITIVE_API_V2_TOKEN=(str, None),
    PHARMACOGNITIVE_CACHING_TIME=(str, None),
    PHARMACOGNITIVE_FIX_BERT_MARKUP=(str, None),
    PHARMACOGNITIVE_MAX_AVAILABLE_PUBLICATIONS=(str, None),
    PHARMACOGNITIVE_TEXT_SCORES_VERSION=(str, None),
    PC_API_SECONDARY_KEY=(str, None),
    PC_API_DDC_ENDPOINT_URL=(str, None),
    PC_API_SECONDARY_CACHING_ENABLED=(str, None),
    PC_API_SECONDARY_CACHING_TIME=(str, None),
    SESSION_COOKIE_SECURE=(bool, True),
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
EDITION = env("EDITION")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS").split(";") if env("CSRF_TRUSTED_ORIGINS") else []
TEST_RUN = env("TEST_RUN")
MERMAID_SERVER_URL = env("MERMAID_SERVER_URL")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_json_widget",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.headless",
    "allauth.usersessions",
    "dj_rest_auth",
    "general",
    "users",
    "kernel",
    "documents",
    "dwh",
    "bibliography",
    "ai_review",
]

try:
    import payment  # noqa

    INSTALLED_APPS.append("payment")
    PAYMENT_ENABLED = True
except ImportError:
    PAYMENT_ENABLED = False


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "base.middlewares.LoggingMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "app.urls"
WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "TEST": {
            "NAME": str(platform.node()),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
            "builtins": ["base.customtags"],
        },
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.path.join(env("REDIS_CONN_STR"), env("REDIS_CACHE_DB")),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
    "chunks": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.path.join(env("REDIS_CONN_STR"), env("REDIS_CHUNKS_DB")),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
    "webchunks": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.path.join(env("REDIS_CONN_STR"), env("REDIS_WEBCHUNKS_DB")),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}


if TEST_RUN:
    CACHES = {
        "default": {
            "BACKEND": "tests.redis_dummy_cache.RedisDummyCache",
        }
    }


CELERY_BROKER_URL = CELERY_RESULT_BACKEND = os.path.join(env("REDIS_CONN_STR"), env("REDIS_BROKER_DB"))
CELERYD_HIJACK_ROOT_LOGGER = True
CELERY_TIMEZONE = "UTC"
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "base.authentication.BearerTokenAuthentication",
        "allauth.account.auth_backends.AuthenticationBackend",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "app.custom_exception_handler.custom_exception_handler",
    "DEFAULT_THROTTLE_RATES": {"ip": "10/5m"},
    "DEFAULT_THROTTLE_ATTEMPTS": {"login": {5: "1m", 6: "5m", 7: "10m", 8: "30m", 9: "60m"}},
}

SPECTACULAR_SETTINGS = {
    "TITLE": "DORA API",
    "VERSION": "1.0.0",
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
}

PHARMACOGNITIVE_API_URL = env("PHARMACOGNITIVE_API_URL")
PHARMACOGNITIVE_API_KEY = env("PHARMACOGNITIVE_API_KEY")
PHARMACOGNITIVE_API_V2_TOKEN = env("PHARMACOGNITIVE_API_V2_TOKEN")
PHARMACOGNITIVE_CACHING_ENABLED = env("PHARMACOGNITIVE_CACHING_ENABLED")
PHARMACOGNITIVE_CACHING_TIME = env("PHARMACOGNITIVE_CACHING_TIME")
PHARMACOGNITIVE_CONTEXT_SEARCH_MODE_ENABLED = env("PHARMACOGNITIVE_CONTEXT_SEARCH_MODE_ENABLED")
PHARMACOGNITIVE_SYNONYMS_SEARCH_MODE_ENABLED = env("PHARMACOGNITIVE_SYNONYMS_SEARCH_MODE_ENABLED")
PHARMACOGNITIVE_FIX_BERT_MARKUP = env("PHARMACOGNITIVE_FIX_BERT_MARKUP")
PHARMACOGNITIVE_MAX_AVAILABLE_PUBLICATIONS = env("PHARMACOGNITIVE_MAX_AVAILABLE_PUBLICATIONS")
PHARMACOGNITIVE_TEXT_SCORES_VERSION = env("PHARMACOGNITIVE_TEXT_SCORES_VERSION")
PC_API_SECONDARY_KEY = env("PC_API_SECONDARY_KEY")
PC_API_DDC_ENDPOINT_URL = env("PC_API_DDC_ENDPOINT_URL")
PC_API_SECONDARY_CACHING_ENABLED = env("PC_API_SECONDARY_CACHING_ENABLED")
PC_API_SECONDARY_CACHING_TIME = env("PC_API_SECONDARY_CACHING_TIME")
EXTERNAL_API_MAX_RETRIES = env.int("EXTERNAL_API_MAX_RETRIES")
EXTERNAL_API_RETRY_WAIT = env.int("EXTERNAL_API_RETRY_WAIT")
EXTERNAL_API_MAX_REQUEST_TIMEOUT = env.int("EXTERNAL_API_MAX_REQUEST_TIMEOUT")
PHARMACOGNITIVE_MAX_REQUEST_TIMEOUT = env.int("PHARMACOGNITIVE_MAX_REQUEST_TIMEOUT")

OPENAI_API_MODEL = env("OPENAI_API_MODEL")
OPENAI_API_BASE_URL = env("OPENAI_API_BASE_URL")
OPENAI_API_VERSION = env("OPENAI_API_VERSION")
OPENAI_API_DEPLOYMENT_NAME = env("OPENAI_API_DEPLOYMENT_NAME")
OPENAI_API_KEY = env("OPENAI_API_KEY")
OPENAI_API_TYPE = env("OPENAI_API_TYPE")
OPENAI_API_TIMEOUT = env.int("OPENAI_API_TIMEOUT")

MINI_OPENAI_API_MODEL = env("MINI_OPENAI_API_MODEL")
MINI_OPENAI_API_BASE_URL = env("MINI_OPENAI_API_BASE_URL")
MINI_OPENAI_API_VERSION = env("MINI_OPENAI_API_VERSION")
MINI_OPENAI_API_DEPLOYMENT_NAME = env("MINI_OPENAI_API_DEPLOYMENT_NAME")
MINI_OPENAI_API_KEY = env("MINI_OPENAI_API_KEY")
BACKUP_MINI_OPENAI_API_MODEL = env("BACKUP_MINI_OPENAI_API_MODEL")
BACKUP_MINI_OPENAI_API_BASE_URL = env("BACKUP_MINI_OPENAI_API_BASE_URL")
BACKUP_MINI_OPENAI_API_VERSION = env("BACKUP_MINI_OPENAI_API_VERSION")
BACKUP_MINI_OPENAI_API_DEPLOYMENT_NAME = env("BACKUP_MINI_OPENAI_API_DEPLOYMENT_NAME")
BACKUP_MINI_OPENAI_API_KEY = env("BACKUP_MINI_OPENAI_API_KEY")

BACKUP_OPENAI_API_MODEL = env("BACKUP_OPENAI_API_MODEL")
BACKUP_OPENAI_API_BASE_URL = env("BACKUP_OPENAI_API_BASE_URL")
BACKUP_OPENAI_API_VERSION = env("BACKUP_OPENAI_API_VERSION")
BACKUP_OPENAI_API_DEPLOYMENT_NAME = env("BACKUP_OPENAI_API_DEPLOYMENT_NAME")
BACKUP_OPENAI_API_KEY = env("BACKUP_OPENAI_API_KEY")
BACKUP_OPENAI_API_TYPE = env("BACKUP_OPENAI_API_TYPE")

IS_BIBLIOGRAPHY_ENABLED = env("IS_BIBLIOGRAPHY_ENABLED")
IS_WEBSEARCH_ENABLED = env("IS_WEBSEARCH_ENABLED")

EMBEDDING_OPENAI_API_CONFIGS = env.json("EMBEDDING_OPENAI_API_CONFIGS")
validate_embedding_openai_api_configs(EMBEDDING_OPENAI_API_CONFIGS, OPENAI_API_TYPE == "azure")

GENERATION_RETRY_TIMES = env("GENERATION_RETRY_TIMES")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.path.join(env("REDIS_CONN_STR"), env("REDIS_CHANNELS_DB"))],
        },
    },
}

PANDAOMICS_CLIENT_API_BASE = env("PANDAOMICS_CLIENT_API_BASE")
PANDAOMICS_CLIENT_TOKEN = env("PANDAOMICS_CLIENT_TOKEN")
PANDAOMICS_CLIENT_USE_SSL = env("PANDAOMICS_CLIENT_USE_SSL")

TOOL_EXECUTION_COUNT_LIMIT = env("TOOL_EXECUTION_COUNT_LIMIT")
TOOL_MAX_EXECUTION_COUNT = env.int("TOOL_MAX_EXECUTION_COUNT")

AGENT_EXECUTOR_MAX_ITERATIONS = env.int("AGENT_EXECUTOR_MAX_ITERATIONS")

TOKEN_ACTIVATION_TIMEOUT = 60 * 60 * 24
TOKEN_PASSWORD_RESET_TIMEOUT = 60 * 60 * 3

FROM_EMAIL = env("FROM_EMAIL")
EMAIL_BACKEND = "django_ses.SESBackend"
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_SES_REGION_NAME = env("AWS_SES_REGION_NAME")
AWS_SES_REGION_ENDPOINT = env("AWS_SES_REGION_ENDPOINT")
AWS_STORAGE_BUCKET = env("AWS_STORAGE_BUCKET")
AWS_STORAGE_REGION = env("AWS_STORAGE_REGION")
S3_ENDPOINT_URL = env("S3_ENDPOINT_URL")

# Azure Blob Storage settings
AZURE_STORAGE_CONNECTION_STRING = env("AZURE_STORAGE_CONNECTION_STRING")
AZURE_STORAGE_CONTAINER = env("AZURE_STORAGE_CONTAINER")
AZURE_STORAGE_LOCATION = env("AZURE_STORAGE_LOCATION")
AZURE_STORAGE_ACCOUNT_NAME = env("AZURE_STORAGE_ACCOUNT_NAME")
AZURE_STORAGE_ACCOUNT_KEY = env("AZURE_STORAGE_ACCOUNT_KEY")
AZURE_STORAGE_AUTO_CREATE_CONTAINER = env("AZURE_STORAGE_AUTO_CREATE_CONTAINER")
AZURE_STORAGE_DOMAIN_SUFFIX = env("AZURE_STORAGE_DOMAIN_SUFFIX")

DORA_PUBLIC_URL = env("DORA_PUBLIC_URL")
DORA_STATIC_URL = env("DORA_STATIC_URL")

MAXIMUM_CONCURRENT_DOCUMENTS_PER_USER = env("MAXIMUM_CONCURRENT_DOCUMENTS_PER_USER")

if not TEST_RUN:
    sentry_sdk.init(
        dsn=env("SENTRY_DSN"),
        integrations=[DjangoIntegration()],
        enable_tracing=True,
        profiles_sample_rate=0.0,  # Disabled due to profiler crashes with certain frame types
        send_default_pii=True,
        environment=env("ENVIRONMENT"),
    )

STRIPE_API_PUBLISHABLE_KEY = env("STRIPE_API_PUBLISHABLE_KEY")
STRIPE_API_SECRET_KEY = env("STRIPE_API_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET")
STRIPE_PRICING_TABLE_ID = env("STRIPE_PRICING_TABLE_ID")
STRIPE_CUSTOMER_PORTAL_RETURN_URL = env("STRIPE_CUSTOMER_PORTAL_RETURN_URL")

FREE_TRIAL_DAYS = 7

HUGGINFACE_API = env("HUGGINFACE_API")
HUGGINFACE_AUTHORIZATION_TOKEN = env("HUGGINFACE_AUTHORIZATION_TOKEN")

X_FRAME_OPTIONS = "SAMEORIGIN"

GENERATION_TASK_TIMEOUT = env.int("GENERATION_TASK_TIMEOUT")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {"level": "INFO", "handlers": ["file", "console"]},
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/dora.log"),
            "formatter": "verbose",
            "when": "midnight",
            "backupCount": 30,
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "formatters": {
        "verbose": {
            "format": ("%(asctime)s [%(levelname)-8s] %(module)s.%(funcName)s %(message)s"),
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
}

# refer to: https://openai.com/api/pricing/
EMBEDDING_MODEL_COST_PER_1M_TOKENS = {"text-embedding-3-small": 0.02}
USE_PHOENIX = env("USE_PHOENIX")
SOCIALACCOUNT_PROVIDERS = env.json("SOCIALACCOUNT_PROVIDERS", default={})
SOCIALACCOUNT_PROVIDERS_GOOGLE_CLIENT_ID = SOCIALACCOUNT_PROVIDERS.get("google", {}).get("client_id")

HEADLESS_CLIENTS = ("browser",)

SITE_ID = 1

HEADLESS_ONLY = True

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = "app.social_login.CustomSocialAccountAdapter"

SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE")

WEBSEARCH_EMBEDDING_REQUEST_INTERVAL = env.int("WEBSEARCH_EMBEDDING_REQUEST_INTERVAL")

SERPER_API_KEY = env("SERPER_API_KEY")
