[uwsgi]
project = dora

chdir = /%(project)
module = app.wsgi:application

env = DJANGO_SETTINGS_MODULE=app.settings

master = true
processes = 10
vacuum = True
max-requests = 5000

buffer-size = 32768
socket = :8080
chmod-socket = 666
harakiri = 3600
socket-timeout = 3600
worker-reload-mercy = 600
reload-mercy = 600
# daemonize = /%(project)/uwsgi.log
