# Generated by Django 4.2 on 2024-06-14 07:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_profile(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("users", "Profile")
    for user in User.objects.all():
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "password_reset_requested_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Password Reset Requested At"),
                ),
                (
                    "password_modified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Password Modified At"),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True, verbose_name="Activated At")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RunPython(create_user_profile, reverse_code=migrations.RunPython.noop),
    ]
