# Generated by Django 4.2 on 2024-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitokenusage",
            name="completion_tokens",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Completion Tokens"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aitokenusage",
            name="prompt_tokens",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Prompt Tokens"),
            preserve_default=False,
        ),
    ]
