# Generated by Django 4.2 on 2024-07-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_aitokenusage_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_stripe_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
