# Generated by Django 4.2 on 2024-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_user_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="terms_and_privacy_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Terms and Privacy Accepted At"),
        ),
        migrations.AlterField(
            model_name="aitokenusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("GEN_PLAN", "Generate Plan"),
                    ("GEN_SECTION", "Generate Section"),
                    ("AI_ACTION", "AI Action"),
                ],
                max_length=20,
            ),
        ),
    ]
