# Generated by Django 4.2 on 2024-08-27 06:11

from django.db import migrations, models

import users.defs


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_terms_and_privacy_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="publication_settings",
            field=models.JSONField(
                default=users.defs.get_default_publication_settings, verbose_name="Publication Settings"
            ),
        ),
        migrations.AlterField(
            model_name="aitokenusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("GEN_PLAN", "Generate Plan"),
                    ("GEN_SECTION", "Generate Section"),
                    ("AI_ACTION", "AI Action"),
                    ("POLISH_SECTION", "Polish Section"),
                ],
                max_length=20,
            ),
        ),
    ]
