# Generated by Django 4.2 on 2024-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_publication_settings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitokenusage",
            name="ai_model",
            field=models.CharField(default="gpt-4o", max_length=30),
        ),
        migrations.AlterField(
            model_name="aitokenusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("GEN_PLAN", "Generate Plan"),
                    ("GEN_SECTION", "Generate Section"),
                    ("AI_ACTION", "AI Action"),
                    ("POLISH_SECTION", "Polish Section"),
                    ("GEN_MERMAID_DIAGRAM", "Generate Mermaid Diagram"),
                    ("CUSTOM_BIB_EMBEDDING", "Generate Custom Bibliography Embedding"),
                    ("WEBSEARCH_EMBEDDING", "Generate Websearch Embedding"),
                ],
                max_length=20,
            ),
        ),
    ]
