# Generated by Django 4.2 on 2024-12-23 06:12

from django.db import migrations, models


def update_default_ai_model(apps, schema_editor):
    AITokenUsage = apps.get_model("users", "AITokenUsage")
    AITokenUsage.objects.filter(ai_model="insilico-cn-gpt-4o").update(ai_model="gpt-4o")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_aitokenusage_ai_model_alter_aitokenusage_usage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitokenusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("GEN_PLAN", "Generate Plan"),
                    ("GEN_SECTION", "Generate Section"),
                    ("AI_ACTION", "AI Action"),
                    ("POLISH_SECTION", "Polish Section"),
                    ("POLISH_DOCUMENT", "Polish Document"),
                    ("GEN_MERMAID_DIAGRAM", "Generate Mermaid Diagram"),
                    ("CUSTOM_BIB_EMBEDDING", "Generate Custom Bibliography Embedding"),
                    ("WEBSEARCH_EMBEDDING", "Generate Websearch Embedding"),
                    ("GEN_DOCUMENT_REVIEW", "Generate Document Review"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(update_default_ai_model),
    ]
