# Generated by Django 4.2 on 2024-12-24 08:41

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models


def set_free_trial_ends_at(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    for profile in Profile.objects.all():
        if profile.activated_at:
            profile.free_trial_ends_at = profile.activated_at + timedelta(days=settings.FREE_TRIAL_DAYS)
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_aitokenusage_usage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="free_trial_ends_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Free Trial Ends At"),
        ),
        migrations.AddField(
            model_name="profile",
            name="free_trial_quota",
            field=models.PositiveIntegerField(
                blank=True, default=3, null=True, verbose_name="Free Trial Quota"
            ),
        ),
        migrations.RunPython(set_free_trial_ends_at, reverse_code=migrations.RunPython.noop),
    ]
