# Generated by Django 4.2 on 2025-01-07 08:06

from django.db import migrations, models

import users.defs


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_free_trial_ends_at_profile_free_trial_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_preferences",
            field=models.JSONField(
                default=users.defs.get_default_display_preferences, verbose_name="Display Preferences"
            ),
        ),
    ]
