# Generated by Django 4.2 on 2025-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_profile_display_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitokenusage",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("GEN_PLAN", "Generate Plan"),
                    ("GEN_SECTION", "Generate Section"),
                    ("AI_ACTION", "AI Action"),
                    ("POLISH_SECTION", "Polish Section"),
                    ("POLISH_DOCUMENT", "Polish Document"),
                    ("GEN_MERMAID_DIAGRAM", "Generate Mermaid Diagram"),
                    ("CUSTOM_BIB_EMBEDDING", "Generate Custom Bibliography Embedding"),
                    ("WEBSEARCH_EMBEDDING", "Generate Websearch Embedding"),
                    ("GEN_DOCUMENT_REVIEW", "Generate Document Review"),
                    ("WORD_FILTERING", "Word Filtering"),
                ],
                max_length=20,
            ),
        ),
    ]
