# Generated by Django 4.2 on 2025-03-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0012_alter_aitokenusage_usage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_usersession",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
