from docx.shared import Inches, Mm
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm

COVER_PAGE_DISCLAIMER_STRING = (
    "Disclaimer: The text of the manuscript below was generated by "
    "<font color='lightblue'><u><a href='https://dora.insilico.com'>Science42: DORA</a></u></font> "
    "platform from <font color='lightblue'><u><a href='https://insilico.com/'>Insilico Medicine</a></u>"
    "</font> using large language models. Please acknowledge and understand that this text shall not "
    "(a) be regarded as Internet news or professional opinions in the medical or biological fields, and "
    "(b) replace the answers from professionals. Since the large language model is not under the control "
    "of Insilico Medicine and it has innate defects that cannot be explained, this manuscript is for your "
    "reference only and it shall not constitute Insilico Medicine’s position or opinions. Insilico Medicine "
    "makes no warranties, implied or express, as to the accuracy and completeness of the manuscript."
)

COVER_PAGE_DATE_STRING = "Generated on {date}"


class PDFPageSizes:
    PAGE_WIDTH, PAGE_HEIGHT = A4
    SPACE_ABOVE_HEADER = 2 * mm
    HEIGHT_HEADER = 19.3 * mm
    WIDTH_LOGO = 64 * mm
    HEIGHT_LOGO = (33.5 - 33.5) * mm
    MARGIN_LEFT = 25.4 * mm
    MARGIN_DOWN = 29 * mm
    MARGIN_DOWN_COVER_PAGE = 52 * mm
    SPACE_BELOW_HEADER = (10 - 10) * mm
    SPACE_ABOVE_TITLE = 10 * mm
    SPACE_ABOVE_DATE = 15 * mm
    SPACE_BETWEEN_PARAGRAPHS = 8 * mm
    SPACE_BETWEEN_REFERENCES = 3 * mm
    MAX_AVAILABLE_HEIGHT = PAGE_HEIGHT - SPACE_ABOVE_HEADER - HEIGHT_HEADER - SPACE_BELOW_HEADER - MARGIN_DOWN
    MAX_AVAILABLE_WIDTH = PAGE_WIDTH - 2 * MARGIN_LEFT
    FIRST_LINE_INDENT = 0.5 * inch


class DocxPageSizes:
    PAGE_WIDTH = Mm(210)
    PAGE_HEIGHT = Mm(297)
    SPACE_ABOVE_HEADER = Mm(3)
    HEIGHT_HEADER = Mm(19.3)
    WIDTH_LOGO = Mm(64)
    HEIGHT_LOGO = Mm(33.5)
    MARGIN_LEFT = Mm(25.4)
    MARGIN_DOWN = Mm(29)
    SPACE_BELOW_HEADER = Mm(10)
    SPACE_ABOVE_TITLE = Mm(10)
    FIRST_LINE_INDENT = Inches(0.5)
    MAX_AVAILABLE_WIDTH = PAGE_WIDTH - 2 * MARGIN_LEFT
    MAX_AVAILABLE_HEIGHT = PAGE_HEIGHT - SPACE_ABOVE_HEADER - HEIGHT_HEADER - SPACE_BELOW_HEADER - MARGIN_DOWN


class FontSizes:
    NORMAL = 11
    HEADING1 = 20
    HEADING2 = 15
    HEADING3 = 12
    HEADING4 = 11
    TITLE = 24
    FOOTER = 10

    @classmethod
    def get_font_size(cls, font_size: int) -> int:
        return getattr(cls, font_size, None)


TITLE_LEADING = 32
NORMAL_LEADING = 15

PUBMED_URL_PATTERN = "https://pubmed.ncbi.nlm.nih.gov/{pmid}/"
PMC_URL_PATTERN = "https://pmc.ncbi.nlm.nih.gov/articles/{pmc_id}/"
DOI_URL_PATTERN = "https://doi.org/{doi}"

HYPERLINK_PATTERN = "<font color='green'><a href='{href}'>{text}</a></font>"

BIB_ID_CHUNK_ID_REFERENCE_PATTERN = r"(BIB_ID:[\w-]+, CHUNK_ID:[\w-]+(?:; BIB_ID:[\w-]+, CHUNK_ID:[\w-]+)*)"
BIB_ID_CHUNK_ID_PATTERN = r"BIB_ID:([\w-]+), CHUNK_ID:([\w-]+)"

UNKNOWN_AUTHOR_NAME = "Unknown"


class ExportFormatType:
    PDF = "pdf"
    DOCX = "docx"
    FORMAT_CHOICES = [PDF, DOCX]


class RGBColors:
    BLACK = (0, 0, 0)
    BLUE = (0, 0, 255)
    DORA_GREEN = (20, 101, 62)
