# Generated by Django 4.2 on 2024-05-31 03:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="XMLTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("template_name", models.CharField(max_length=255, verbose_name="Template Name")),
                ("template_version", models.PositiveIntegerField(verbose_name="Template Version")),
                ("template_xml", models.TextField(verbose_name="Template XML")),
                (
                    "template_xml_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="templates",
                        verbose_name="XML Template File",
                    ),
                ),
                ("template_to_json", models.JSONField(verbose_name="Template to JSON")),
                ("template_to_dict", models.JSONField(verbose_name="Template to Dict")),
                (
                    "sorted_sections",
                    models.JSONField(blank=True, default=dict, null=True, verbose_name="Sorted Sections"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "template_json",
                    models.JSONField(
                        help_text="Available tools: ['PandaOmics_combined_diff_expression', 'PandaOmics_combined_diff_methylation', 'PandaOmics_comparisons_diff_expression', 'PandaOmics_comparisons_diff_methylation', 'PandaOmics_evidence_from_Knowledge_graph', 'pubmed_abstract_similarity_search_tool']",
                        verbose_name="Template JSON",
                    ),
                ),
                ("template_file", models.FileField(upload_to="templates", verbose_name="Template File")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
