# Generated by Django 4.2 on 2025-05-16 08:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kernel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("name", models.TextField(verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
                ("api_key", models.TextField(blank=True, verbose_name="API Key")),
                ("last_sync", models.DateTimeField(blank=True, null=True, verbose_name="Last Sync")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "suggest_type",
                    models.CharField(
                        choices=[("agent", "Agent"), ("resource", "Resource"), ("source", "Source")],
                        max_length=30,
                        verbose_name="Suggest Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("icon", models.CharField(blank=True, null=True)),
                ("resources", models.JSONField(blank=True, default=list)),
                ("toggleable", models.BooleanField()),
                ("description", models.TextField(blank=True)),
                ("display_name", models.CharField(max_length=255)),
                ("checked_by_default", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=999)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[("mcp", "mcp"), ("pandaomics", "pandaomics"), ("local", "local")],
                        max_length=10,
                    ),
                ),
                ("args", models.JSONField(default=list)),
                ("path", models.TextField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("get", "get"),
                            ("post", "post"),
                            ("put", "put"),
                            ("delete", "delete"),
                            ("patch", "patch"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolPromptInstruction",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("instruction", models.TextField()),
                ("name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kernel.tool")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ToolPromptInstructionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("name", models.TextField(unique=True)),
                ("empty_state", models.TextField(blank=True, null=True)),
                ("names_placeholder", models.TextField(blank=True, null=True)),
                ("instructions_placeholder", models.TextField(blank=True, null=True)),
                (
                    "tool_instructions",
                    models.ManyToManyField(related_name="groups", to="kernel.toolpromptinstruction"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="template",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="template",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_templates",
                to="auth.group",
                verbose_name="Allowed Groups",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Allowed Users",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="display_order",
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AddField(
            model_name="template",
            name="free_trial",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the template is available for free trial.",
                verbose_name="Free Trial",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the template is currently online.",
                verbose_name="Is Online",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_json",
            field=models.JSONField(verbose_name="Template JSON"),
        ),
        migrations.DeleteModel(
            name="XMLTemplate",
        ),
        migrations.AddField(
            model_name="templateagent",
            name="tools",
            field=models.ManyToManyField(blank=True, null=True, to="kernel.tool"),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="kernel.tool", verbose_name="Tools"
            ),
        ),
    ]
