# Generated by Django 4.2 on 2025-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernel", "0002_mcpserver_suggestion_templateagent_tool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateagent",
            name="tools",
            field=models.ManyToManyField(blank=True, to="kernel.tool"),
        ),
    ]
